### ISSUE TITLE
Vibration sensor is broken after app exit

### ISSUE THREAD

**Issue by sirAvent** [sirAvent/color-switch#3]
Seems like an issue in page's onDestroy() function. Exiting the app causes the user's watch to stop vibrating unless restarted.

**Comment by fwz233** [comment]
> 

你好，我也遇见了这个问题，根据我的开发经验，应该是你没有用 .stop 函数注销震动传感器。
Hello, I also encountered this problem. According to my development experience, it should be that you are useless The stop function logs off the vibration sensor.

**Comment by fwz233** [comment]
> Seems like an issue in page's onDestroy() function. Exiting the app causes the user's watch to stop vibrating unless restarted.

为什么要怎么写？vibrate && vibrate.stop()😂
直接vibrate.stop()不就可以吗。
Why and how?vibrate && vibrate.stop() 😂Isn't it OK to directly use vibrate. Stop().

**Comment by sirAvent** [comment]
Yeah it is okay to use them. The issue here is that the timer, playInterval has already been stopped when calling timer.stop(playInterval) causing an error that results in vibrate stop to not run. Will fix in an update 😂

**Comment by fwz233** [comment]
> 
老哥做的这个软件真的很好玩
😂华米除了gtr4/gts4系列，还有一个对标Apple Watch ultra的新品，国外应该还没有预热，但是在中国他们透露了这个产品
This software is really fun.😂
In addition to the gtr 4 / gts 4 series, huami also has a new product of the standard Apple Watch ultra, which should not be warmed up abroad, but they revealed it in China
